server:
  port: 8081

spring:
  thymeleaf:
    cache: false
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/day1010?characterEncoding=UTF-8&serverTimezone=GMT%2B8
      username: root
      password: 123456

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

